import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        paddingTop: 50,
        backgroundColor: "#F4F6FF",
      },
      quoteBox: {
        shadowColor: "#171717",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.7,
        backgroundColor: "#fff",
        shadowRadius: 3,
        borderRadius: 3,
        padding: 5,
        elevation: 5,
        marginTop: 10,
      },
      quoteText: {
        padding: 10,
        backgroundColor: "white",
        borderRadius: 5,
        textAlign: "center",
      },
      sectionTitle: {
        fontWeight: "500",
        fontSize: 18,
        marginTop: 30,
      },
      friendList: {
        marginTop: 15,
      },
      friendItem: {
        marginHorizontal: 5,
        padding: 10,
        backgroundColor: "#f0f0f0",
        borderRadius: 10,
        alignItems: "center",
      },
      friendInfo: {
        flexDirection: "row",
        alignItems: "center",
        borderColor: "rgba(0,0,0,0.1)",
        borderBottomWidth: 1,
        padding: 10,
      },
      friendName: {
        fontWeight: "bold",
        fontSize: 16,
        marginLeft: 10,
      },
      friendStatus: {
        color: "#717070",
        fontWeight: "400",
        fontSize: 12,
      },
      nearbyList: {
        marginTop: 15,
      },
      logoText: {
        fontFamily: "Arial",
        fontSize: 24,
        color: "#00A8E8", 
        fontWeight: "bold", 
        letterSpacing: 0.5, 
      },
      postInput: {
        backgroundColor: '#F4F6FF',
        height: 50,
        padding: 15,
        width: 245,
        borderRadius: 25,
      },
      postButton: {
        borderRadius: 50,
        backgroundColor: '#00A8E8',
        height: 50,
        width: 50,
        justifyContent: 'center',
        alignItems: 'center',
      },
      box: {
        marginBottom: 10,
        padding: 10,
        paddingVertical: 20,
        width: '100%',
        backgroundColor: '#F4F6FF',
        borderRadius: 8,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
        shadowColor: '#171717',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.7,
        backgroundColor: '#fff',
        shadowRadius: 3,
        elevation: 2,
      },
      actionContainer: {
        flexDirection: 'row',
        marginTop: -10,
        alignItems: 'center',
        justifyContent: 'space-around',
      },
      postIcon: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
      },
});
