import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  startContainer: {
    height: '100%',
    width: '100%',
    justifyContent: 'flex-end',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
  },
  overlayContainer: {
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  textContainer: {
    alignItems: 'flex-start',
    paddingTop: 80,
  },
  buttonContainer: {
    alignItems: 'center',
    paddingBottom: 40,
  },
  bigText: {
    fontSize: 42,
    color: '#fff',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  big: {
    fontSize: 64,
    marginTop: 50,
    
  },
  subText: {
    fontSize: 16,
    color:'#fff',
    lineHeight: 25,
    marginTop: 10,
    marginLeft: 8,
  },
  button: {
    backgroundColor: '#00712D',
    paddingVertical: 15,
    paddingHorizontal: 60,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonText: {
    color: 'white',
    fontSize: 20,
    fontWeight: '600',
    marginRight: 10,
  },
  loginContainer: {
    flex: 1,
    backgroundColor: '#00712D',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 100,
  },
  whiteBackground: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
    height: '100%',
    paddingTop: 100,
    width: '100%',
    alignItems: 'center',
  },
  loginHeader: {
    fontSize: 22,
    color: '#000',
    textAlign: 'center',
    fontWeight: '600',
    marginBottom: 20,
  },
  inputField: {
    width: '100%',
    borderColor: 'rgba(0, 0, 0, 0.2)',
    borderWidth: 1,
    borderRadius: 25,
    padding: 15,
    marginBottom: 15,
    backgroundColor: '#f9f9f9',
  },
  loginButton: {
    backgroundColor: '#00712D',
    paddingVertical: 15,
    paddingHorizontal: 60,
    borderRadius: 25,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  loginButtonText: {
    color: 'white',
    fontSize: 20,
    fontWeight: '600',
  },
  signUpText: {
    marginTop: 20,
    fontSize: 16,
    color: 'rgba(0,0,0,0.6)',
  },
  signUpLink: {
    color: '#00712D',
    fontWeight: 'bold',
  },
  mainContainer: {
    paddingHorizontal: 10,
    paddingBottom:0,
    backgroundColor: '#fff',
    flex: 1,
  },
  headerText: {
    fontWeight: 'bold',
    fontSize: 24,
    marginBottom: 10,
  },
  welcomeText: {
    fontSize: 18,
    marginBottom: 20,
  },
  descriptionText: {
    fontSize: 16,
    color: 'rgba(0,0,0,0.7)',
    lineHeight: 25,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginVertical: 10,
  },
  attractionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  highlight:{
    fontWeight:'bold',
    color:'rgba(0,0,0,0.8)',
  },  
  boxContainer: {
    width: '48%',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: 10,
    overflow: 'hidden',
  },
  boxImageHolder: {
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  placeImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  attractionText: {
    padding: 10,
    fontWeight: '600',
    textAlign: 'center',
  },
  updatesContainer: {
    marginTop: 20,
  },
  updateText: {
    fontSize: 16,
    color: 'rgba(0,0,0,0.6)',
    textAlign:'justify',
  },
  contactContainer: {
    padding: 10,
    paddingVertical:30,
    justifyContent:'center',
  },
  contactHeader: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  getInTouchHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 15,
  },
  contactList: {
    flexDirection: 'row',
    alignItems: 'center',

    marginVertical: 5,
  },
  bulletPoint: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#32CD32', 
    marginRight: 10,
  },
  contactInfo: {
    fontSize: 16,
    color: 'rgba(0,0,0,0.8)',
  },
  footerText: {
    fontSize: 14,
    marginTop: 20,
    color: 'rgba(0,0,0,0.6)',
    textAlign: 'center',
  },
  errorText:{
    color:"#FA4032",
    marginVertical:10,
  },
  description:{
    width:"70%",
    textAlign:'center',
    marginVertical:8,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    width: '80%',
  },
  headerText: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  input: {
    width: '100%',
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    marginBottom: 10,
    paddingLeft: 10,
    borderRadius: 5,
  },
  updatesList: {
    width: '100%',
    marginTop: 20,
  },
  updateItem: {
    backgroundColor: '#fff',
    padding: 15,
    marginBottom: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  updateTitle: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  updateDescription: {
    fontSize: 16,
    marginTop: 5,
  },
  feedbackList: {
    marginBottom: 20,
  },
  feedbackItem: {
    backgroundColor: '#fff',
    padding: 15,
    marginBottom: 15,
    width:330,
    borderRadius: 10,
    shadowColor: '#000',
    borderColor:"#DDD",
    borderWidth:1,
  },
  usernameFeedback: {
    fontSize: 18,
    fontWeight: '600',
    color: '#007BFF',
    marginBottom: 8,
  },
  feedbackText: {
    fontSize: 16,
    color: '#555',
    lineHeight: 22,
  },
  noFeedbackText: {
    textAlign: 'center',
    fontSize: 18,
    color: '#888',
    marginTop: 20,
  },
  feadbackHeader: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 20,
  },
});
export default styles;
